# -*- coding: utf-8 -*-
"""Copy of colab.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I6-Cu-QQwhJqtPukF26fsZVPc3aF60ns
"""

import random
import math
# Taking Inputs
lower = int(input("Enter Lower bound:- "))
# Taking Inputs
upper = int(input("Enter Upper bound:- "))
# generating random number between
# the lower and upper

x=random.randint(lower, upper)
print("\n\tyou've only",
      round(math.log(upper - lower+1,2)),
      "changes to guess the integer!\n")

# initializing the number of guesses.
count = 0

# for calculation of minimum number of
# guesses depends upon range
while count <math.log(upper - lower + 1,2):
     count += 1

     # taking guessing number as input
     guess = int(input("Guess a number:- "))

     # condioning testing
     if x == guess:
         print("Congratulations you did it in ",
               count, " try")
         # once guessed, loop will break
         break
     elif x > guess:
         print("You Guessed too small!")
     elif x < guess:
         print("You Guessed too high!")

# If guessing is more than required guesses,
# shows this output.
if count >= math.log(upper - lower + 1,2):
    print("\nThe number is %d" % x)
    print("\tBetter Luck Next time!")

# Better to use this source code on pycharm!